---
title: "Assignment 3 Report"
author: "Alex Tsiofas"
date: "26/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Info

January 29th, 2021
GitHub Repository Link: https://github.com/atsiofas/432A3.git
Github Username: atsiofas

```{r warning = F, message = F}
library(dplyr)
```

### Loading the Dataset
```{r}
dat <- read.csv("./InputData/FallopiaData.csv")
dat$Nutrients <- as.factor(dat$Nutrients)
```

### Working with the data

```{r}

wrangled_dat <- dat %>% 
  filter(Total >= 60) %>% #to remove values less than 60 we filter to keep values greater than or equal to 60
  select(Total, Taxon, Scenario, Nutrients) %>% #this line reorders the columns of dat to the specified sequence, any column name not listed is removed
  mutate(TotalG = Total*0.001) %>% #this will create the new TotalG column, converting the total amounts from milligrams to grams by multiplying the mg values by 0.001
  select(-Total) #this removes the Total column, so TotalG replaces Total

```

### Custom Function

this function takes two inputs and - a vector of data and a string defining the calculation done to the vector

```{r}
#no default arguments, vector and type need to be specified by the user
my_calc <- function(vec, type) {
  if (type == "Average"){
    return(mean(vec)) #if string entered is "average", return mean of the vector 
  } else if (type == "Sum"){
    return(sum(vec)) #if string is sum, return sum of the vector values
  } else if (type == "Observations"){
    return(length(vec)) #if string entered is "Observations", return the number of observations or length of the vector
  } else {
    print("Error, unrecognized calculation type") #error statement printed if string doesnt match any of the above, not returned
  }
}

#calculate the number of observations in the Taxon column
my_calc(wrangled_dat$Taxon, "Observations")

#using this function to calculate mean of TotalG column in the two nutrient categories

#filtering for low nutrients
filtered_dat <- filter(wrangled_dat, Nutrients == 'low')
#calculating the mean TotalG for low nutrient entries and storing the value
low_total_mean <- my_calc(filtered_dat$TotalG, "Average")
#filtering for high nutrients
filtered_dat <- filter(wrangled_dat, Nutrients == 'high')
#calculating the mean TotalG for high nutrient entries and storing the value
high_total_mean <- my_calc(filtered_dat$TotalG, "Average")

print(paste("Low Nutrient Average TotalG: ", low_total_mean, ", High Nutrient Average TotalG: ", high_total_mean))
```



